The MintDuino Reflex Game will test the reflexes of two players.  The game takes place on the small Mini-Breadboard, with each player waiting to push a button when an LED in the center of the breadboard lights up.  The central yellow LED will light up after a random amount of time has passed (something between say 5 and 10 seconds).  Whichever player pushes their button first after the central LED lights up wins and a green LED will light up on the side of the player who wins.  But a player can't simply push the button over and over before the LED lights up!  Pushing the button before the center LED lights up automatically gives the other player the win.

That's The Big Project, but let's break it down into four sub-tasks that will help us understand the proper wiring of the MintDuino and the electronics components and the programming elements required:

. Wire up and program the MintDuino to light an LED - this will help us to not only light the center yellow LED but also the winning player's green LED.
. Wire up and light an LED after a Random Wait Time- we will learn how to light an LED after waiting a random amount of time.
. Wire up and program an LED to light up when the pushbutton is pressed - this will help us to understand the proper wiring of a pushbutton as well as how to use it as a trigger for another event (lighting an LED in this case).
.  Wire and program two pushbuttons to light up a pushbutton's matching LED when pressed - Now we'll figure out how to trigger the correct LED when its paired pushbutton is pressed.

Once we understand what's required to light LEDs, wait a random amount of time, and test for pushbuttons to be pressed, we can pull it all together and build the MintDuino Reflex Game.  The fact that we'll have multiple LEDS shouldn't be a problem - if we know how to light one, well... we can light two... or three.  And if we know how to determine if a pushbutton has been pressed, we can probably figure out how to detect which of two pushbuttons has been pressed.  Then we add some code to start the game, check for a pre-mature button push, and reset the game... and we're in business.

====
This MintDuino Notebook will provide you with the sample code required to test various circuits and electronics components, but it will not be able to provide a comprehensive tutorial on programming the MintDuino (or an Arduino).  If you need a better understanding of the programming language used to create MintDuino sketches, you’ll want to turn to a variety of online and printed sources designed to teach beginning Arduino programming.  A few of these resources can be found at the end of this document.

yes!
====

