DCPS Error Log

== Error 1

book.xml:434: element xref: validity error : Syntax of value for attribute linkend of xref is not valid


----
<simpara>Connect two jumper wires to the pushbutton as shown in <xref linkend="Figure 10"/>.  One jumper wire is inserted in the first hole at the top row of the pushbutton and the second jumper wire is inserted in the empty bottom row of the mini breadboard.</simpara>


----
== Error 4

book.xml:441: element xref: validity error : Syntax of value for attribute linkend of xref is not valid


----
<simpara>Next, add a single 100ohm resistor (this resistor will be referred to as RES2 to the mini breadboard as shown in <xref linkend="Figure 11"/>.  This resistor (RES2) will have one of its leads inserted into the row where the first resistor (RES1) is inserted and the jumper wire goes to GND.  The other lead for RES2 can be inserted in a row just above the pushbutton.</simpara>


----
== Error 7

book.xml:448: element xref: validity error : Syntax of value for attribute linkend of xref is not valid


----
<simpara>As shown in <xref linkend="Figure 12"/>, insert the top jumper wire of the pushbutton into the row containing only a RES2 lead (the one not sharing GND with RES1) and insert the bottom jumper wire of the pushbutton into the bottom (empty) row of the mini breadboard (which will serve as +5V supply for the mini breadboard).</simpara>


----
== Error 10

book.xml:455: element xref: validity error : Syntax of value for attribute linkend of xref is not valid


----
<simpara>Finally, add two more jumper wires – insert one into the bottom row of the mini breadboard that will also go to +5V on the MintDuino – we’ll call this the JUMPV.  The other jumper wire will be inserted where the pushbutton’s top jumper wire and RES2 are inserted and this new jumper wire will go to Digital Pin 4 (or Pin 6 on the ATmega chip) – we’ll call this JUMP4.  Both of these new jumper wires can be seen in <xref linkend="Figure 13"/>.</simpara>


----
== Error 13

book.xml:549: element xref: validity error : IDREF attribute linkend references an unknown ID "Figure 12"


----


----
== Error 16

book.xml:549: element xref: validity error : IDREF attribute linkend references an unknown ID "Figure 11"


----


----
== Error 19

book.xml:549: element xref: validity error : IDREF attribute linkend references an unknown ID "Figure 13"


----


----
== Error 22

book.xml:549: element xref: validity error : IDREF attribute linkend references an unknown ID "Figure 10"


----


----
